# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3edda5335279d1f3bd67bcc32d5b8ab42d42d8723be69da1974a71a4b16835f05e330431cd88dbe22efa10942726043292144da43a3ac333e2fba3f404c046e

test:
  secret_key_base: 6ef11183cd5e3b9fde2f1dc63448bdcbb38f7afaa2dadb95d861585235b387857052f6cce3d55820c6b323559e9d57e9358e65ddef177ec3dcbceaafe67a13ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
